environment:
    matrix:
        - PYTHON: "C:\\Python27"

build:

build_script: 
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build . --config Release --target PACKAGE
    - cp Release/ck-crowdnode-server.exe .
    - cd ..
    - "%PYTHON%/python.exe -m run_tests.py"
    - rm ck-crowdnode-server.exe

artifacts:
    - path: build/*.exe
      name: CK Crowdnode Server installer
