environment:
    matrix:
        - PYTHON: "C:\\Python27"

build:

build_script: 
    - mkdir build
    - cd build
    - cmake ..
    - msbuild /p:Configuration=Release /p:Platform=Win32 C:/projects/ck-crowdnode/build/Project.sln
    - ls C:/projects/ck-crowdnode/build
    - ls Release
    - cp Release/ck-crowdnode-server.exe .
    - cd ..
    - "%PYTHON%/python.exe -m run_tests.py"

artifacts:
    - path: build/Release/ck-crowdnode-server.exe
      name: CK Crowdnode Server Executable
