
build:

build_script: 
    - mkdir build
    - cd build
    - cmake ..
    - ls C:/projects/ck-crowdnode/build
    - msbuild /p:Configuration=Release /p:Platform=Win32 C:/projects/ck-crowdnode/build/Project.sln
