environment:
    matrix:
        - PYTHON: "C:\\Python27"

build:

build_script: 
    - mkdir build
    - cd build
    - cmake ..
    # - msbuild /p:Configuration=Release /p:Platform=Win32 C:/projects/ck-crowdnode/build/Project.sln
    - cmake --build . --config Release --target PACKAGE
    - cp Release/ck-crowdnode-server.exe .
    - cd ..
    - "%PYTHON%/python.exe -m run_tests.py"

artifacts:
    - path: build/Release/ck-crowdnode-server.exe
      name: CK Crowdnode Server Executable

    - path: build/*.msi
      name: CK Crowdnode Server installer

    - path: build/*.exe
      name: CK Crowdnode Server installer EXE
